Create dependencies.py
noob-hackers/Infect pull request #16
Opened 2020-08-28 08:09 UTC by krishpranav

Hi I have added a new python file 
this will help the user to install all the dependencies quickly

2020-10-18 13:45 UTC, Omicron166yt requested changes
There are 2 things that don't make a lot of sense but the code is good

2020-10-18 13:45 UTC, Omicron166yt commented on dependencies.py
> +os.system("clear")
Why generate a banner if right after you are going to remove it?
For that it is better not to put any banner

2020-10-18 13:45 UTC, Omicron166yt commented on dependencies.py
> +agreement()
Correct me if I'm wrong
It is not necessary to create a function in this case as it will only be used once

2020-10-19 04:17 UTC, noob-hackers commented
Thanks for suggesting but we used bash Scripting not Python so ...we dont
need python code 🙄

On Sun, 18 Oct, 2020, 7:15 pm Omicron166yt, <notifications@github.com>
wrote:

> *@Omicron166yt* requested changes on this pull request.
>
> There are 2 things that don't make a lot of sense but the code is good
> ------------------------------
>
> In dependencies.py
> <https://github.com/noob-hackers/Infect/pull/16#discussion_r507154090>:
>
> > +os.system("apt install figlet")
> +os.system("figlet INSTALLATION")
> +os.system("clear")
>
> Why generate a banner if right after you are going to remove it?
> For that it is better not to put any banner
> ------------------------------
>
> In dependencies.py
> <https://github.com/noob-hackers/Infect/pull/16#discussion_r507154732>:
>
> > +def agreement():
> +  if agree in Y:
> +    os.system("figlet INSTALLING THE DEPENDENCIES")
> +    time.sleep(0.5)
> +    os.system("apt update")
> +    os.system("apt upgrade")
> +    os.system("pkg upgrade")
> +    os.system("pkg install git")
> +    os.system("pkg install python -y")
> +    os.system("pip install lolcat")
> +    os.system("clear")
> +    os.system("figlet INSTALLATION COMPLETED...")
> +    print("you can now run infect.sh")
> +  elif agree in N:
> +    print("This tool needs some depedencies please run python3 dependencies.py")
> +    print("exiting")
> +    exit()
> +
> +agreement()
>
> Correct me if I'm wrong
> It is not necessary to create a function in this case as it will only be
> used once
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/noob-hackers/Infect/pull/16#pullrequestreview-511146027>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL2ISEBMKISYNRVB4OJ27GTSLLWORANCNFSM4QN3OAGQ>
> .
>

2020-10-19 05:42 UTC, krishpranav commented
ok thank you

2020-10-19 05:42 UTC, closed without merging